# Generated by Django 4.1 on 2022-10-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='the_type',
            field=models.CharField(choices=[['type1', 'type2'], ['type2', 'type2'], ['type3', 'type3'], ['type4', 'type4'], ['type5', 'type5'], ['type6', 'type6'], ['type7', 'type7']], max_length=20),
        ),
    ]
