# Generated by Django 4.1 on 2022-10-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
