# Generated by Django 4.1 on 2022-10-14 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
