# Generated by Django 4.1 on 2022-10-14 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_imageproduct_product_delete_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
