# Generated by Django 4.1 on 2022-10-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convertapp', '0005_remove_convertaudio_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertaudio',
            name='image',
            field=models.ImageField(null=True, upload_to='audio'),
        ),
    ]
