# Generated by Django 4.1 on 2022-10-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convertapp', '0006_convertaudio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertaudio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='audio'),
        ),
    ]
