# Generated by Django 4.1 on 2022-10-05 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convertapp', '0007_alter_convertaudio_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convertaudio',
            name='image',
        ),
    ]
