# Generated by Django 4.1 on 2022-10-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convertapp', '0008_remove_convertaudio_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convertaudio',
            name='audio',
        ),
        migrations.AddField(
            model_name='convertaudio',
            name='link',
            field=models.CharField(max_length=220, null=True),
        ),
    ]
