# Generated by Django 4.1 on 2022-10-05 22:26

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('convertapp', '0009_remove_convertaudio_audio_convertaudio_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertaudio',
            name='map_data',
            field=models.FileField(null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='maps'),
        ),
    ]
